### ISSUE TITLE
HCERT file

### ISSUE THREAD

**Issue by jakubvano** [ehn-dcc-development/eu-dcc-hcert-spec#102]
Are there any recommendations / guidelines on how to create a file containing HCERT data?  

We are considering sharing DCCs from Wallet app to third party mobile applications on the same device. Most appropriate option seems to be creating a HCERT file and transporting it via standard OS mechanisms. Besides content of the file we would need to define a file extension, mime type and UTI (iOS / OSX environment).

One option we are considering would be to rely on CBOR file format definition, with `.cbor` file extension and `application/cbor` MIME type, Unfortunately, no standard UTI seems to be defined.
Another option could be to define a custom format, e.g. with `.hcert` file extension, `application/hcert` MIME type and `public.hcert` UTI.

Thanks for any pointer / insight.

**Comment by abowody70** [comment]
Abowody

**Comment by abowody70** [comment]
@abowody70

**Comment by abowody70** [comment]
123456

**Comment by abowody70** [comment]
[123456]()

**Comment by ryanbnl** [comment]
We've provided a specification for a validation service to allow some use cases which avoid the need to transfer all the data to random apps.
