### ISSUE TITLE
List of public keys

### ISSUE THREAD

**Issue by alexandernajafi** [ehn-dcc-development/eu-dcc-hcert-spec#110]
Not sure if this is the correct forum, but where can I find all published public keys for verification? Do each participating country publish their public key on their own or is there a list of all published keys for all participating countries?

**Comment by jschlyter** [comment]
Each country, e.g., [Sweden](https://dgcg.covidbevis.se/tp/), has their own list fetch from the EU gateway.

**Comment by ryanbnl** [comment]
We'll add a list to the overview repository, I made an issue there, should have it up this week:

https://github.com/ehn-dcc-development/eu-dcc-overview/issues/19
