### ISSUE TITLE
Allow vac-certs nested in COVID-Tests

### ISSUE THREAD

**Issue by jucktnich** [ehn-dcc-development/eu-dcc-hcert-spec#111]
Allow the nesting of (parts of) an vaccination cert in an Test-Cert. The reason for this is, that for example in Germany there are 2G+-rules, which means ((vaccinated && tested)||(recovered && tested)), so have to show your vaccination/recovered AND you're tested cert, so it would be cool, to only show on cert.
### Solution 1
Just put two certs in one code. (Big QR-Code size needed)
### Solution 2
The testing site scans you're vac-cert, sends it to the signer, and the signer adds parts of the vac-cert to your test cert (relatively small QR-Code needed)

**Comment by dokaha** [comment]
i nearly opened a duplicate for this...
Also in austria we need to proof 2G+ (vaccination and PCR test) in a single qr code.

**Comment by jschlyter** [comment]
Except for the schema, there's nothing in the HCERT that disallows multiple results in one payload. The DCC schema had an explicit restriction added to only allow a single test/rec/vacc. Please raise this issue https://github.com/ehn-dcc-development/ehn-dcc-schema as it is not part of the core HCERT spec.

It should be worth mentioning that multiple HCERTs in a single QR code is undefined and will not work. The optical encoding only allows for a single HCERT.

**Comment by jucktnich** [comment]
@jschlyter could you transfer this issue, or should I close this and open a new one

**Comment by vaubaehn** [comment]
> It should be worth mentioning that multiple HCERTs in a single QR code is undefined and will not work. The optical encoding only allows for a single HCERT.

There are obviously some ideas, to place a second HCERT into the unprotected COSE header. While this may work in theory, I suspect that such "combined" QR codes are most often not readable practically, as their size would be >1.4KB, and our scanners already often have problems with single ~700B QR codes...

**Comment by vaubaehn** [comment]
@jucktnich I don't have much hope, even if you open a new issue in [xxx](https://github.com/ehn-dcc-development/ehn-dcc-schema), because of https://github.com/ehn-dcc-development/ehn-dcc-schema/issues/110#issuecomment-907308313 and following...

(FYI @jschlyter )

**Comment by jucktnich** [comment]
@vaubaehn the problem you stated only applies to my solution 1

**Comment by vaubaehn** [comment]
@jucktnich
The problem that I stated here https://github.com/ehn-dcc-development/hcert-spec/issues/111#issuecomment-988142722 covers your solution 1 - the QR code size may be too big to scan in many cases.
The problem that I linked here https://github.com/ehn-dcc-development/ehn-dcc-schema/issues/110#issuecomment-907308313 covers your solution 2 - that solution is not ehn-dcc-schema compliant and changing this would need much political effort as this already had been rejected by the EU legal department.

**Comment by jucktnich** [comment]
Yeah the legal problem is hard to mitigate, but maybe the EU changes their mind.
