### ISSUE TITLE
Relax requirement for country code of issuer

### ISSUE THREAD

**Issue by martin-lindstrom** [ehn-dcc-development/eu-dcc-hcert-spec#88]
The latest version of the DCC schema now allows organization identifiers where we future expected a ISO 3166-1 alpha-2 country code (for example UNHCR). So we should re-phrase the requirement that we currently have for the `iss` claim.

**Comment by grischard** [comment]
This could already be a problem with Kosovo, which doesn't have an ISO 3166-1 alpha-2 country code for complicated reasons, and where the customary XK should be specified.

**Comment by ryanbnl** [comment]
@martin-lindstrom do you still wish to propose this? seems to be a minor / non-breaking change, however in practise the `iss` claim isn't really used for much, however the system is in maintenance mode now..

**Comment by ryanbnl** [comment]
Closing as the DCC is considered stable and no changes are foreseen.
